### ISSUE TITLE
Investigate LTO issue seen with AArch64 builds

### ISSUE THREAD

**Issue by andreiw** [intel/unicorn-for-efi#2]
There is an AArch64 issue where due to LTO the build of UnicornSampleArm64
takes forever and then bombs out complaining about missing __ashrti3.
A workaround is to modify the EDK2 Conf/tools_def.txt to avoid LTO.

**Comment by yli147** [comment]
A temporary workaound for the issue is to add -fno-lto to  unicorn/efi/UnicornArm64Lib.inf  , with this change we do not need to modify the EDK2 Conf/tools_def.txt to avoid LTO.

[BuildOptions.AARCH64]
GCC:*_*_*_CC_FLAGS = -I$(MODULE_DIR)/../qemu/tcg/aarch64 -fno-lto

**Comment by yli147** [comment]
Need dig more to see which code in UnicornArm64Lib.inf has issue with LTO

**Comment by yli147** [comment]
This issue is caused by the gcc flag "-flto" to the below two files.
  - unicorn/qemu/accel/tcg/translate-all.c   <= line 132, the macro TB_FOR_EACH_TAGGED causes a lot of link time if with -flto GCC flag
  - unicorn/qemu/exec.c   <= line 906,  gcc lto is not working well with Int128 shift operation (complaining about missing __ashrti3.)

If you manually build these two files with -fno-lto option by using the below commands, then the whole build process will be success

"aarch64-linux-gnu-gcc" -MMD -MF ./Build/Unicorn/RELEASE_GCC5/AARCH64/unicorn/efi/UnicornArm64Lib/OUTPUT/qemu/exec.obj.deps  -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -ffunction-sections -fdata-sections -DSTRING_ARRAY_NAME=UnicornArm64LibStrings -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -mlittle-endian -fno-short-enums -fverbose-asm -funsigned-char -ffunction-sections -fdata-sections -Wno-address -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-pic -fno-pie -ffixed-x18 -mcmodel=small -flto -Wno-unused-but-set-variable -Wno-unused-const-variable -nostdinc  -I./unicorn/efi/../include -I./unicorn/efi/../qemu -I./unicorn/efi/../qemu/include -I./unicorn/efi/../qemu/tcg -I./unicorn/efi/../qemu/target/arm -I./unicorn/efi/../glib_compat -include aarch64.h -DCONFIG_TARGET_HEADER=\"config-target-aarch64.h\" -DUNICORN_FOR_EFI -DUNICORN_HAS_ARM64 -DNEED_CPU_H -DUNICORN_FOR_EFI_INTERNAL -I./unicorn/efi/../qemu/tcg/aarch64 -Wno-psabi -c -o ./Build/Unicorn/RELEASE_GCC5/AARCH64/unicorn/efi/UnicornArm64Lib/OUTPUT/qemu/exec.obj -I./unicorn/qemu/target/arm -I./unicorn/qemu/accel/tcg -I./unicorn/qemu/tcg -I./unicorn/qemu/fpu -I./unicorn/qemu/softmmu -I./unicorn/qemu -I./unicorn/efi -I./Build/Unicorn/RELEASE_GCC5/AARCH64/unicorn/efi/UnicornArm64Lib/DEBUG -I./MdePkg -I./MdePkg/Include -I./MdePkg/Test/UnitTest/Include -I./MdePkg/Include/AArch64 -I./MdeModulePkg -I./MdeModulePkg/Include -I./unicorn/efi/include -I./unicorn/include/unicorn -I./unicorn/efi/.. ./unicorn/qemu/exec.c -fno-lto
"aarch64-linux-gnu-gcc" -MMD -MF ./Build/Unicorn/RELEASE_GCC5/AARCH64/unicorn/efi/UnicornArm64Lib/OUTPUT/qemu/accel/tcg/translate-all.obj.deps  -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -ffunction-sections -fdata-sections -DSTRING_ARRAY_NAME=UnicornArm64LibStrings -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -mlittle-endian -fno-short-enums -fverbose-asm -funsigned-char -ffunction-sections -fdata-sections -Wno-address -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-pic -fno-pie -ffixed-x18 -mcmodel=small -flto -Wno-unused-but-set-variable -Wno-unused-const-variable -nostdinc  -I./unicorn/efi/../include -I./unicorn/efi/../qemu -I./unicorn/efi/../qemu/include -I./unicorn/efi/../qemu/tcg -I./unicorn/efi/../qemu/target/arm -I./unicorn/efi/../glib_compat -include aarch64.h -DCONFIG_TARGET_HEADER=\"config-target-aarch64.h\" -DUNICORN_FOR_EFI -DUNICORN_HAS_ARM64 -DNEED_CPU_H -DUNICORN_FOR_EFI_INTERNAL -I./unicorn/efi/../qemu/tcg/aarch64 -Wno-psabi -c -o ./Build/Unicorn/RELEASE_GCC5/AARCH64/unicorn/efi/UnicornArm64Lib/OUTPUT/qemu/accel/tcg/translate-all.obj -I./unicorn/qemu/target/arm -I./unicorn/qemu/accel/tcg -I./unicorn/qemu/tcg -I./unicorn/qemu/fpu -I./unicorn/qemu/softmmu -I./unicorn/qemu -I./unicorn/efi -I./Build/Unicorn/RELEASE_GCC5/AARCH64/unicorn/efi/UnicornArm64Lib/DEBUG -I./MdePkg -I./MdePkg/Include -I./MdePkg/Test/UnitTest/Include -I./MdePkg/Include/AArch64 -I./MdeModulePkg -I./MdeModulePkg/Include -I./unicorn/efi/include -I./unicorn/include/unicorn -I./unicorn/efi/.. ./unicorn/qemu/accel/tcg/translate-all.c -fno-lto

**Comment by yli147** [comment]
> A temporary workaound for the issue is to add -fno-lto to unicorn/efi/UnicornArm64Lib.inf , with this change we do not need to modify the EDK2 Conf/tools_def.txt to avoid LTO.
> 
> [BuildOptions.AARCH64] GCC:____*_CC_FLAGS = -I$(MODULE_DIR)/../qemu/tcg/aarch64 -fno-lto

https://github.com/intel/unicorn-for-efi/pull/3

**Comment by andreiw** [comment]
What is the difference in overall binary size? Can you investigate the __ashrti3 issue?

**Comment by andreiw** [comment]
__ashrti3 is an easy fix:

```
diff --git a/ArmPkg/Library/GccLto/liblto-aarch64.a b/ArmPkg/Library/GccLto/liblto-aarch64.a
index 6ca3932f1cf3..d9e10910e107 100644
Binary files a/ArmPkg/Library/GccLto/liblto-aarch64.a and b/ArmPkg/Library/GccLto/liblto-aarch64.a differ
diff --git a/ArmPkg/Library/GccLto/liblto-aarch64.s b/ArmPkg/Library/GccLto/liblto-aarch64.s
index 02a55ef4456c..496512284583 100644
--- a/ArmPkg/Library/GccLto/liblto-aarch64.s
+++ b/ArmPkg/Library/GccLto/liblto-aarch64.s
@@ -19,3 +19,4 @@
   .long memset - .
   .long __stack_chk_fail - .
   .long __stack_chk_guard - .
+  .long __ashrti3 - .
```

**Comment by andreiw** [comment]
@yli147 how did you narrow the long link time to TB_FOR_EACH_TAGGED?

**Comment by yli147** [comment]
> __ashrti3 is an easy fix:
> 
> ```
> diff --git a/ArmPkg/Library/GccLto/liblto-aarch64.a b/ArmPkg/Library/GccLto/liblto-aarch64.a
> index 6ca3932f1cf3..d9e10910e107 100644
> Binary files a/ArmPkg/Library/GccLto/liblto-aarch64.a and b/ArmPkg/Library/GccLto/liblto-aarch64.a differ
> diff --git a/ArmPkg/Library/GccLto/liblto-aarch64.s b/ArmPkg/Library/GccLto/liblto-aarch64.s
> index 02a55ef4456c..496512284583 100644
> --- a/ArmPkg/Library/GccLto/liblto-aarch64.s
> +++ b/ArmPkg/Library/GccLto/liblto-aarch64.s
> @@ -19,3 +19,4 @@
>    .long memset - .
>    .long __stack_chk_fail - .
>    .long __stack_chk_guard - .
> +  .long __ashrti3 - .
> ```

yes, that is.  a similar finding for this.  trying to move the fix from the edk2 ArmPkg to the unicron-for-efi project,  so that we do not need to upstream this change for __ashrti3 to edk repo.

**Comment by yli147** [comment]
> @yli147 how did you narrow the long link time to TB_FOR_EACH_TAGGED?

Suspect the WPA stage generates too many new object files (which is in intermediate language) for the later ltrans optimization stage.
Thus we need to optimize the ltrans stage in prallel to speed up the LTO process ,  -fto=auto seems speed up the thing
https://gcc.gnu.org/onlinedocs/gccint/LTO-Overview.html

**Comment by yli147** [comment]
-fto=auto seems speed up thing

**Comment by andreiw** [comment]
Should be resolved as of https://github.com/intel/unicorn-for-efi/commit/7141cce4026940aee5aada785eb6163e86729a74
